import { NextRequest, NextResponse } from "next/server";
import { RequirementsRecord } from "@/lib/types";

// Field display order — mirrors FIELDS in the Streamlit pdf_service.py
const FIELDS: Array<[keyof RequirementsRecord, string]> = [
  ["version_control", "1. Version Control"],
  ["ide", "2. IDE / Editor"],
  ["code_push", "3. How Do You Push the Code?"],
  ["deployment", "4. Deployment Approaches"],
  ["architecture", "5. Architecture Patterns"],
  ["design_patterns", "6. Design Patterns"],
  ["orm", "7. ORM"],
  ["additional_requirements", "8. Additional Requirements"],
];

function formatTimestamp(iso: string): string {
  if (!iso) return "";
  return iso.replace("T", " ").replace("Z", " UTC");
}

export async function POST(req: NextRequest) {
  let record: RequirementsRecord;
  try {
    record = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  // Dynamically import jsPDF so it only loads at runtime (not during build).
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginL = 20;
  const marginR = 20;
  const contentW = pageW - marginL - marginR;
  const headerH = 36;

  // Brand colours
  const BRAND_BG: [number, number, number] = [30, 58, 95];
  const BRAND_FG: [number, number, number] = [255, 255, 255];
  const BRAND_FG_MUTED: [number, number, number] = [180, 205, 230];
  const LABEL_COLOR: [number, number, number] = [30, 58, 95];
  const BODY_COLOR: [number, number, number] = [71, 85, 105];
  const DIVIDER_COLOR: [number, number, number] = [226, 232, 240];
  const FOOTER_COLOR: [number, number, number] = [148, 163, 184];

  function drawHeader() {
    // Brand bar
    doc.setFillColor(...BRAND_BG);
    doc.rect(0, 0, pageW, headerH, "F");
    doc.setTextColor(...BRAND_FG);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(17);
    doc.text("Learn It Here - Project Requirements", marginL, 13);
    const submittedAt = record.submitted_at
      ? formatTimestamp(record.submitted_at)
      : "";
    if (submittedAt) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...BRAND_FG_MUTED);
      doc.text(`Submitted: ${submittedAt}`, marginL, 23);
    }
  }

  function drawFooter() {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...FOOTER_COLOR);
    doc.text(
      "Generated by Learn It Here  |  Powered by Next.js & Neon DB  |  learnit.here",
      pageW / 2,
      pageH - 8,
      { align: "center" }
    );
  }

  // First page
  drawHeader();
  drawFooter();

  let y = headerH + 10;

  for (const [key, label] of FIELDS) {
    const value = (record[key] ?? "").toString().trim();
    if (!value) continue;

    // Check if we need a new page (leave room for footer)
    if (y + 30 > pageH - 20) {
      doc.addPage();
      drawHeader();
      drawFooter();
      y = headerH + 10;
    }

    // Label
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...LABEL_COLOR);
    const labelLines = doc.splitTextToSize(label, contentW);
    doc.text(labelLines, marginL, y);
    y += labelLines.length * 7 + 1;

    // Value (may wrap)
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...BODY_COLOR);
    const valueLines = doc.splitTextToSize(value, contentW - 6);

    // Page-break mid-field if needed
    for (const line of valueLines) {
      if (y + 7 > pageH - 20) {
        doc.addPage();
        drawHeader();
        drawFooter();
        y = headerH + 10;
      }
      doc.text(line, marginL + 6, y);
      y += 6;
    }
    y += 2;

    // Divider
    doc.setDrawColor(...DIVIDER_COLOR);
    doc.line(marginL, y, pageW - marginR, y);
    y += 5;
  }

  const pdfBytes = Buffer.from(doc.output("arraybuffer"));

  return new NextResponse(pdfBytes, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": "attachment; filename=project_requirements.pdf",
    },
  });
}
