"""PDF generation for project-requirements submissions.

The previous implementation hand-painted the header bar once at the top of
the document, which meant any answer long enough to push content onto a
second page rendered without the header *or* the footer. This rewrite uses
FPDF's ``header()`` / ``footer()`` lifecycle hooks so every page picks up
the brand chrome automatically.
"""

from __future__ import annotations

from collections.abc import Iterable
from datetime import datetime, timezone

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from models import RequirementsRecord

# ── Field map ────────────────────────────────────────────────────────────────
# (record_key, display_label) — order is the order that appears in the PDF.
FIELDS: tuple[tuple[str, str], ...] = (
    ("version_control", "1. Version Control"),
    ("ide", "2. IDE / Editor"),
    ("code_push", "3. How Do You Push the Code?"),
    ("deployment", "4. Deployment Approaches"),
    ("architecture", "5. Architecture Patterns"),
    ("design_patterns", "6. Design Patterns"),
    ("orm", "7. ORM"),
    ("additional_requirements", "8. Additional Requirements"),
)


# ── Helpers ──────────────────────────────────────────────────────────────────
def _safe(text: object) -> str:
    """Strip characters outside Latin-1 for built-in PDF fonts."""
    return str(text or "").encode("latin-1", "replace").decode("latin-1")


def _format_timestamp(iso_ts: str) -> str:
    """Turn an ISO 8601 timestamp into a human-readable form for the header."""
    if not iso_ts:
        return ""
    if "T" in iso_ts:
        return iso_ts.replace("T", " ").replace("Z", " UTC")
    return iso_ts


# ── PDF document ─────────────────────────────────────────────────────────────
class RequirementsPDF(FPDF):
    """A branded PDF document for a single requirements submission.

    Subclassing ``FPDF`` and overriding ``header()`` / ``footer()`` means
    those bands are repainted on *every* page automatically — so a long
    "Additional Requirements" entry that spills onto page 2 still gets the
    brand bar at the top and the attribution strip at the bottom.
    """

    BRAND_BG = (30, 58, 95)
    BRAND_FG = (255, 255, 255)
    BRAND_FG_MUTED = (180, 205, 230)
    LABEL_COLOR = (30, 58, 95)
    BODY_COLOR = (71, 85, 105)
    DIVIDER_COLOR = (226, 232, 240)
    FOOTER_COLOR = (148, 163, 184)

    def __init__(self, submitted_at: str = ""):
        super().__init__()
        self.set_margins(20, 46, 20)  # top margin clears the 36 px brand bar
        self.set_auto_page_break(auto=True, margin=20)
        self._submitted_at = submitted_at

    # FPDF lifecycle: called automatically on every add_page() and overflow.
    def header(self) -> None:  # noqa: D401 - FPDF API name
        self.set_fill_color(*self.BRAND_BG)
        self.rect(0, 0, 210, 36, "F")
        self.set_text_color(*self.BRAND_FG)
        self.set_font("Helvetica", "B", 17)
        self.set_xy(20, 9)
        self.cell(
            0,
            10,
            _safe("Learn It Here - Project Requirements"),
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
        )
        if self._submitted_at:
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*self.BRAND_FG_MUTED)
            self.set_x(20)
            self.cell(
                0,
                7,
                _safe(f"Submitted: {_format_timestamp(self._submitted_at)}"),
                new_x=XPos.LMARGIN,
                new_y=YPos.NEXT,
            )
        # Drop back to body position
        self.set_y(46)

    def footer(self) -> None:  # noqa: D401 - FPDF API name
        self.set_y(-18)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self.FOOTER_COLOR)
        self.cell(
            0,
            8,
            _safe(
                "Generated by Learn It Here  |  Powered by Streamlit & Supabase  |  learnit.here"
            ),
            align="C",
        )

    def render_field(self, label: str, value: str) -> None:
        """Render one (label, answer, divider) block."""
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*self.LABEL_COLOR)
        self.multi_cell(0, 7, _safe(label))

        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.BODY_COLOR)
        self.set_x(26)
        self.multi_cell(0, 6, _safe(value))
        self.ln(2)

        self.set_draw_color(*self.DIVIDER_COLOR)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(5)


# ── Public API ───────────────────────────────────────────────────────────────
def generate_pdf(
    record: RequirementsRecord,
    *,
    fields: Iterable[tuple[str, str]] = FIELDS,
) -> bytes:
    """Generate a PDF byte string for a requirements submission.

    The ``record`` is treated as a plain mapping — anything matching a key
    in ``fields`` is rendered, anything missing or empty is skipped.
    """
    submitted_at = record.get(
        "submitted_at",
        datetime.now(timezone.utc).isoformat(),
    )
    pdf = RequirementsPDF(submitted_at=submitted_at)
    pdf.add_page()
    for field_key, display_label in fields:
        answer = record.get(field_key, "")
        if not answer:
            continue
        pdf.render_field(display_label, answer)
    return bytes(pdf.output())
