import re
from datetime import datetime, timezone
from fpdf import FPDF


def _safe(text) -> str:
    """Strip characters outside Latin-1 for built-in PDF fonts."""
    return str(text or "").encode("latin-1", "replace").decode("latin-1")


def generate_pdf(data: dict) -> bytes:
    from fpdf import FPDF
    from fpdf.enums import XPos, YPos

    FIELDS = [
        ("version_control",   "1. Version Control"),
        ("ide",               "2. IDE / Editor"),
        ("code_push",         "3. How Do You Push the Code?"),
        ("deployment",        "4. Deployment Approaches"),
        ("architecture",      "5. Architecture Patterns"),
        ("design_patterns",   "6. Design Patterns"),
        ("orm",               "7. ORM"),
        ("additional_requirements", "8. Additional Requirements"),
    ]

    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.add_page()

    # ── Header bar ──────────────────────────────────────────────────────────
    pdf.set_fill_color(30, 58, 95)
    pdf.rect(0, 0, 210, 36, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 17)
    pdf.set_xy(20, 9)
    pdf.cell(0, 10, "Learn It Here - Project Requirements", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(180, 205, 230)
    ts = data.get("submitted_at", datetime.now(timezone.utc).isoformat())
    # Make ISO timestamp human-readable for PDF display
    ts_display = ts.replace("T", " ").replace("Z", " UTC") if "T" in ts else ts
    pdf.set_x(20)
    pdf.cell(0, 7, f"Submitted: {ts_display}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Body ─────────────────────────────────────────────────────────────────
    pdf.set_y(46)
    for field, label in FIELDS:
        answer = data.get(field, "")
        if not answer:
            continue
        # Question label
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 58, 95)
        pdf.multi_cell(0, 7, _safe(label))
        # Answer text
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(71, 85, 105)
        pdf.set_x(26)
        pdf.multi_cell(0, 6, _safe(answer))
        pdf.ln(2)
        # Divider
        pdf.set_draw_color(226, 232, 240)
        pdf.line(20, pdf.get_y(), 190, pdf.get_y())
        pdf.ln(5)

    # ── Footer ───────────────────────────────────────────────────────────────
    pdf.set_y(-18)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(
        0, 8,
        "Generated by Learn It Here  |  Powered by Streamlit & Supabase  |  learnit.here",
        align="C",
    )

    return bytes(pdf.output())


# ── Supabase Storage ──────────────────────────────────────────────────────────

