"""SQL query comparison cheat sheet across SQL Server, Oracle, and PostgreSQL."""

import streamlit as st

from components.content import code_block, paragraph, section_intro, section_title, subsection


def render_sql_query_comparison() -> None:
    section_title(
        "SQL Server vs Oracle vs PostgreSQL Queries",
        "Quick CRUD and SELECT query patterns side-by-side.",
    )
    section_intro(
        "Use this page as a copy-ready cheat sheet for the most common SQL operations "
        "across SQL Server, Oracle, and PostgreSQL."
    )

    subsection("0) Setup sample table")
    paragraph("Create a comparable Customers table in each database.")
    code_block(
        "-- SQL Server\n"
        "CREATE TABLE customers (\n"
        "    customer_id INT IDENTITY(1,1) PRIMARY KEY,\n"
        "    customer_guid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),\n"
        "    customer_name NVARCHAR(100) NOT NULL UNIQUE,\n"
        "    email NVARCHAR(255) NOT NULL,\n"
        "    created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME()\n"
        ");\n\n"
        "-- Oracle\n"
        "CREATE TABLE customers (\n"
        "    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
        "    customer_guid RAW(16) DEFAULT SYS_GUID() NOT NULL,\n"
        "    customer_name VARCHAR2(100) NOT NULL UNIQUE,\n"
        "    email VARCHAR2(255) NOT NULL,\n"
        "    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL\n"
        ");\n\n"
        "-- PostgreSQL\n"
        "CREATE TABLE customers (\n"
        "    customer_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n"
        "    customer_guid UUID NOT NULL DEFAULT gen_random_uuid(),\n"
        "    customer_name VARCHAR(100) NOT NULL UNIQUE,\n"
        "    email VARCHAR(255) NOT NULL,\n"
        "    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n"
        ");",
        language="sql",
    )

    subsection("1) CREATE / INSERT")
    code_block(
        "-- SQL Server\n"
        "INSERT INTO customers (customer_name, email)\n"
        "VALUES ('Alice', 'alice@example.com');\n\n"
        "-- Oracle\n"
        "INSERT INTO customers (customer_name, email)\n"
        "VALUES ('Alice', 'alice@example.com');\n\n"
        "-- PostgreSQL\n"
        "INSERT INTO customers (customer_name, email)\n"
        "VALUES ('Alice', 'alice@example.com');",
        language="sql",
    )

    subsection("2) READ / SELECT basics")
    paragraph("Select all rows, select specific columns, and filter with WHERE.")
    code_block(
        "-- SQL Server\n"
        "SELECT * FROM customers;\n"
        "SELECT customer_id, customer_name FROM customers WHERE customer_name = 'Alice';\n\n"
        "-- Oracle\n"
        "SELECT * FROM customers;\n"
        "SELECT customer_id, customer_name FROM customers WHERE customer_name = 'Alice';\n\n"
        "-- PostgreSQL\n"
        "SELECT * FROM customers;\n"
        "SELECT customer_id, customer_name FROM customers WHERE customer_name = 'Alice';",
        language="sql",
    )

    subsection("3) TOP 10 / pagination")
    code_block(
        "-- SQL Server\n"
        "SELECT TOP 10 customer_id, customer_name, created_at\n"
        "FROM customers\n"
        "ORDER BY created_at DESC;\n\n"
        "-- Oracle (12c+)\n"
        "SELECT customer_id, customer_name, created_at\n"
        "FROM customers\n"
        "ORDER BY created_at DESC\n"
        "FETCH FIRST 10 ROWS ONLY;\n\n"
        "-- PostgreSQL\n"
        "SELECT customer_id, customer_name, created_at\n"
        "FROM customers\n"
        "ORDER BY created_at DESC\n"
        "LIMIT 10;",
        language="sql",
    )

    subsection("4) Date comparison in WHERE")
    code_block(
        "-- SQL Server: last 30 days\n"
        "SELECT *\n"
        "FROM customers\n"
        "WHERE created_at >= DATEADD(DAY, -30, SYSDATETIME());\n\n"
        "-- Oracle: last 30 days\n"
        "SELECT *\n"
        "FROM customers\n"
        "WHERE created_at >= SYSTIMESTAMP - INTERVAL '30' DAY;\n\n"
        "-- PostgreSQL: last 30 days\n"
        "SELECT *\n"
        "FROM customers\n"
        "WHERE created_at >= NOW() - INTERVAL '30 days';",
        language="sql",
    )

    subsection("5) Conversion functions (CAST / CONVERT / TO_*)")
    code_block(
        "-- SQL Server\n"
        "SELECT TOP 1\n"
        "    CAST(customer_id AS VARCHAR(20)) AS customer_id_text,\n"
        "    CONVERT(VARCHAR(10), created_at, 23) AS created_date_yyyy_mm_dd, -- style 23 = YYYY-MM-DD\n"
        "    TRY_CONVERT(INT, '123') AS safe_int\n"
        "FROM customers;\n\n"
        "-- Oracle\n"
        "SELECT\n"
        "    TO_CHAR(customer_id) AS customer_id_text,\n"
        "    TO_CHAR(created_at, 'YYYY-MM-DD') AS created_date_yyyy_mm_dd,\n"
        "    TO_NUMBER('123') AS safe_int\n"
        "FROM customers\n"
        "FETCH FIRST 1 ROW ONLY;\n\n"
        "-- PostgreSQL\n"
        "SELECT\n"
        "    customer_id::TEXT AS customer_id_text,\n"
        "    TO_CHAR(created_at, 'YYYY-MM-DD') AS created_date_yyyy_mm_dd,\n"
        "    CAST('123' AS INT) AS safe_int\n"
        "FROM customers\n"
        "LIMIT 1;",
        language="sql",
    )

    subsection("6) GUID/UUID creation and using it in queries")
    paragraph("Generate a new GUID/UUID, insert with it, then query by it.")
    code_block(
        "-- SQL Server\n"
        "DECLARE @new_guid UNIQUEIDENTIFIER = NEWID();\n"
        "INSERT INTO customers (customer_guid, customer_name, email)\n"
        "VALUES (@new_guid, 'Bob', 'bob@example.com');\n"
        "SELECT * FROM customers WHERE customer_guid = @new_guid;\n\n"
        "-- Oracle\n"
        "INSERT INTO customers (customer_guid, customer_name, email)\n"
        "VALUES (SYS_GUID(), 'Bob', 'bob@example.com');\n"
        "SELECT RAWTOHEX(customer_guid) AS customer_guid_hex, customer_name\n"
        "FROM customers\n"
        "WHERE customer_name = 'Bob';\n\n"
        "-- PostgreSQL\n"
        "WITH new_id AS (\n"
        "    SELECT gen_random_uuid() AS id\n"
        ")\n"
        "INSERT INTO customers (customer_guid, customer_name, email)\n"
        "SELECT id, 'Bob', 'bob@example.com'\n"
        "FROM new_id;\n"
        "SELECT * FROM customers WHERE customer_name = 'Bob';",
        language="sql",
    )

    subsection("7) UPDATE")
    code_block(
        "-- SQL Server\n"
        "UPDATE customers\n"
        "SET email = 'alice.new@example.com'\n"
        "WHERE customer_name = 'Alice';\n\n"
        "-- Oracle\n"
        "UPDATE customers\n"
        "SET email = 'alice.new@example.com'\n"
        "WHERE customer_name = 'Alice';\n\n"
        "-- PostgreSQL\n"
        "UPDATE customers\n"
        "SET email = 'alice.new@example.com'\n"
        "WHERE customer_name = 'Alice';",
        language="sql",
    )

    subsection("8) DELETE")
    code_block(
        "-- SQL Server\n"
        "DELETE FROM customers WHERE customer_name = 'Bob';\n\n"
        "-- Oracle\n"
        "DELETE FROM customers WHERE customer_name = 'Bob';\n\n"
        "-- PostgreSQL\n"
        "DELETE FROM customers WHERE customer_name = 'Bob';",
        language="sql",
    )

    subsection("9) UPSERT (important day-to-day pattern)")
    code_block(
        "-- SQL Server\n"
        "MERGE customers AS target\n"
        "USING (SELECT 'Alice' AS customer_name, 'alice@example.com' AS email) AS source\n"
        "ON target.customer_name = source.customer_name\n"
        "WHEN MATCHED THEN\n"
        "    UPDATE SET target.email = source.email\n"
        "WHEN NOT MATCHED THEN\n"
        "    INSERT (customer_name, email)\n"
        "    VALUES (source.customer_name, source.email);\n\n"
        "-- Oracle\n"
        "MERGE INTO customers c\n"
        "USING (SELECT 'Alice' AS customer_name, 'alice@example.com' AS email FROM dual) s\n"
        "ON (c.customer_name = s.customer_name)\n"
        "WHEN MATCHED THEN\n"
        "    UPDATE SET c.email = s.email\n"
        "WHEN NOT MATCHED THEN\n"
        "    INSERT (customer_name, email)\n"
        "    VALUES (s.customer_name, s.email);\n\n"
        "-- PostgreSQL\n"
        "INSERT INTO customers (customer_name, email)\n"
        "VALUES ('Alice', 'alice@example.com')\n"
        "ON CONFLICT (customer_name)\n"
        "DO UPDATE SET email = EXCLUDED.email;",
        language="sql",
    )

    subsection("10) Transactions (basic and important)")
    code_block(
        "-- SQL Server\n"
        "BEGIN TRAN;\n"
        "UPDATE customers SET email = 'tx@example.com' WHERE customer_name = 'Alice';\n"
        "COMMIT;\n\n"
        "-- Oracle\n"
        "UPDATE customers SET email = 'tx@example.com' WHERE customer_name = 'Alice';\n"
        "COMMIT;\n\n"
        "-- PostgreSQL\n"
        "BEGIN;\n"
        "UPDATE customers SET email = 'tx@example.com' WHERE customer_name = 'Alice';\n"
        "COMMIT;",
        language="sql",
    )

    subsection("Quick notes")
    st.markdown(
        "- Prefer **parameterized queries** from application code (avoid string-concatenated SQL).\n"
        "- Always test `UPDATE`/`DELETE` filters with a `SELECT` first.\n"
        "- Keep indexes on columns frequently used in `WHERE`, `JOIN`, and `ORDER BY`."
    )
