[theme]
primaryColor             = "#2D6A4F"
backgroundColor          = "#F8F8F8"
secondaryBackgroundColor = "#EFEFED"
textColor                = "#1A1A1A"
font                     = "sans serif"

[server]
headless            = true

[browser]
gatherUsageStats    = false
